apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlops-major-deployment
  labels:
    app: mlops-major
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mlops-major
  template:
    metadata:
      labels:
        app: mlops-major
    spec:
      containers:
        - name: mlops-major
          image: saurabh0112/mlops-major:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
          readinessProbe:
            httpGet:
              path: /
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 5000
            initialDelaySeconds: 30
            periodSeconds: 30
